table 'Employee Territories'
	lineageTag: 0c2e984d-862a-4f3b-8339-9df8cbecbdc6

	column 'Employee Id'
		dataType: int64
		formatString: 0
		lineageTag: ea350392-a019-42c2-9e97-40b748dfd7a9
		summarizeBy: none
		sourceColumn: Employee Id

		annotation SummarizationSetBy = Automatic

	column territory_id
		dataType: string
		lineageTag: 2e798ab2-25d7-45c4-9ef7-5eea38f930ff
		summarizeBy: none
		sourceColumn: territory_id

		annotation SummarizationSetBy = Automatic

	column 'public.territories.territory_description'
		dataType: string
		lineageTag: 65ee0913-08d9-40c6-b4d0-fc597f110aa6
		summarizeBy: none
		sourceColumn: public.territories.territory_description

		annotation SummarizationSetBy = Automatic

	column 'public.territories.region_id'
		dataType: int64
		formatString: 0
		lineageTag: cd90e878-d2eb-420f-82ae-8f9c7c036c12
		summarizeBy: sum
		sourceColumn: public.territories.region_id

		annotation SummarizationSetBy = Automatic

	partition 'Employee Territories-8057ab52-610b-4720-8e9b-ee46c2a61e04' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "Northwind"),
				    public_employee_territories = Source{[Schema="public",Item="employee_territories"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(public_employee_territories,{"public.employees"}),
				    #"Expanded public.territories" = Table.ExpandRecordColumn(#"Removed Columns", "public.territories", {"territory_id", "territory_description", "region_id", "public.employee_territories", "public.region"}, {"public.territories.territory_id", "public.territories.territory_description", "public.territories.region_id", "public.territories.public.employee_territories", "public.territories.public.region"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded public.territories",{"public.territories.public.employee_territories", "public.territories.public.region", "public.territories.territory_id"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns1",{{"employee_id", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"employee_id", "Employee Id"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

